"""item pictures and capture mode

Revision ID: 5f7e41134fe9
Revises: 57fbf2d737cc
Create Date: 2026-09-21 00:35:05.580157
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '5f7e41134fe9'
down_revision: str | None = '57fbf2d737cc'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_images',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('source_photo_id', sa.Uuid(), nullable=True),
    sa.Column('box', sa.JSON(), nullable=True),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('bytes', sa.Integer(), nullable=True),
    sa.Column('mime', sa.String(length=60), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_photo_id'], ['photos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_images_item_id'), 'item_images', ['item_id'], unique=False)
    op.create_index(op.f('ix_item_images_sha256'), 'item_images', ['sha256'], unique=False)
    op.create_index(op.f('ix_item_images_source_photo_id'), 'item_images', ['source_photo_id'], unique=False)
    op.create_index('uq_item_images_primary', 'item_images', ['item_id'], unique=True, postgresql_where=sa.text('is_primary'))
    # Autogenerate wrote this as a bare NOT NULL column, which cannot be added to a table
    # that already has rows in it - every existing photograph would have no value for it.
    # A server default fills them in (they were all scenes; the single-object mode did not
    # exist yet), and dropping the default afterwards leaves the column exactly as the
    # model describes it, with the value supplied by the application from here on.
    op.add_column(
        'photos',
        sa.Column('mode', sa.String(length=10), nullable=False, server_default='scene'),
    )
    op.alter_column('photos', 'mode', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'mode')
    op.drop_index('uq_item_images_primary', table_name='item_images', postgresql_where=sa.text('is_primary'))
    op.drop_index(op.f('ix_item_images_source_photo_id'), table_name='item_images')
    op.drop_index(op.f('ix_item_images_sha256'), table_name='item_images')
    op.drop_index(op.f('ix_item_images_item_id'), table_name='item_images')
    op.drop_table('item_images')
    # ### end Alembic commands ###
